---
title: "STA304PS4JCodeAppendix2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# Load Packages
library(haven)
library(tidyverse)
library(labelled)
library(jtools)
library(boot)
```

```{r}
raw_data <- read_dta("ns20200625.dta")

# Add Labels
raw_data <- labelled::to_factor(raw_data)
```


```{r}
select_data <- raw_data %>%
  dplyr::select(vote_2020,
                age,
                gender,
                race_ethnicity,
                census_region,
                language
  )
```

```{r}
clean_data <- select_data %>%
  na.omit() %>%
  filter(vote_2020 %in% c("Joe Biden", "Donald Trump"))
```

```{r}
clean_data <- clean_data %>%
  mutate(age_group = cut(age, 
                         breaks = c(18, 30, 40, 50, 60, 100), 
                         right = FALSE,
                         labels = c("18 to 29", 
                                    "30 to 39", 
                                    "40 to 49", 
                                    "50 to 59",
                                    "60 +")
                         ),
         race_ethnicity = case_when(race_ethnicity == "Black, or African American" ~ "Black, or African American",
                                    race_ethnicity == "White" ~ "White",
                                    race_ethnicity != "Black, or African American" | race_ethnicity != "White" ~ "Other"),
         language = case_when(language == "Yes, we speak Spanish." ~ "Spanish",
                              language == "Yes, we speak a language other than Spanish or English." ~ "Other",
                              language == "No, we speak only English." ~ "English")

           
  )
```

# 2.2 Display of Survey Data

```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = vote_2020)) + 
  geom_bar(colour="black", fill = 'blue') + 
  labs(title = "Graph 1: Vote Decisions of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       ) + 
  theme_minimal()

```



```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = age_group)) + 
  geom_bar(colour = "black", fill = "darkturquoise") +
  labs(title = "Graph 2: Age Proportions of Respondents", 
       x = "Age",
       y = "Number of Respondents"
       ) + 
  theme_minimal()
```

```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = gender)) + 
  geom_bar(colour = "black", fill = "firebrick2") + 
  labs(title = "Graph 3: Gender Proportions of Respondents", 
       x = "Gender",
       y = "Number of Respondents"
       ) +
  theme_minimal()

```

```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = race_ethnicity)) + 
  geom_bar(colour = "black", fill = "orangered1") + 
  labs(title = "Graph 4: Races of Respondents", 
       x = "Race",
       y = "Number of Respondents"
       ) + 
  coord_flip() + 
  theme_minimal()
```

```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = language)) + 
  geom_bar(colour = "black", fill = "springgreen4") + 
  labs(title = "Graph 5: Languages Used by Respondents", 
       x = "Language Used at Home",
       y = "Number of Respondents"
       ) + 
  theme_minimal()

```

```{r, echo=FALSE}
clean_data %>% 
  ggplot(aes(x = census_region)) + 
  geom_bar(colour = "black", fill = "mediumseagreen") + 
  labs(title = "Graph 6: Regional Distribution of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       ) +
  theme_minimal()
```


# 2.3 ACS Data

```{r, include=FALSE}
raw_strat_data <- read_dta("usa_00002.dta")
```

```{r, include=FALSE}
raw_strat_data <- labelled::to_factor(raw_strat_data)
```

```{r, include=FALSE}
raw_select_strat_data <- raw_strat_data %>%
  select(age,
         sex,
         race,
         hispan,
         bpl,
         region,
         language,
         empstat
    
  )
```

```{r, include=FALSE}
strat_data <- raw_select_strat_data %>% 
  na.omit()
```

```{r, include=FALSE}
clean_strat_data <-
  strat_data %>%
  select(region, 
         sex, 
         age, 
         race, 
         bpl, 
         language) %>% 
  rename(gender = sex, 
         race_ethnicity = race, 
         census_region = region,
         foriegn_born = bpl)
```

```{r, include=FALSE}
clean_strat_data <- clean_strat_data %>%
  mutate(age_group = cut(as.numeric(age), 
                         breaks = c(18, 30, 40, 50, 60, 100), 
                         right = FALSE,
                         labels = c("18 to 29", 
                                    "30 to 39", 
                                    "40 to 49", 
                                    "50 to 59",
                                    "60 +")
                         ),
         census_region = case_when(census_region == "new england division" ~ "Northeast",
                                  census_region == "middle atlantic division" ~ "Northeast",
                                  census_region == "east north central div" ~ "Midwest",
                                  census_region == "west north central div" ~ "Midwest",
                                  census_region == "south atlantic division" ~ "South",
                                  census_region == "east south central div" ~ "South",
                                  census_region == "west south central div" ~ "South",
                                  census_region == "mountain division" ~ "West",
                                  census_region == "pacific division" ~ "West"
                                  ),
         language = case_when(language == "english" ~ "English",
                              language == "spanish" ~ "Spanish",
                              language != "english" | language != "spanish" ~ "Other"
                              ),
         race_ethnicity = case_when(race_ethnicity == "black/african american/negro" ~ "Black, or African American",
                                    race_ethnicity == "white" ~ "White",
                                    race_ethnicity != "black/african american/negro" | race_ethnicity != "white" ~ "Other"
                                    ),
         gender = case_when(gender == "male" ~ "Male",
                            gender == "female" ~ "Female")



         

    
  )
```

```{r, include=FALSE}
# Remove Data that doesn't fit the groups
clean_strat_data <- clean_strat_data %>%
  na.omit() %>%
  labelled::to_factor()
```

# 2.4 Display ACS Data

```{r, echo=FALSE}
clean_strat_data %>% 
  ggplot(aes(x = age_group)) + 
  geom_bar(colour = "black", fill = "darkturquoise") +
  labs(title = "Graph 7: Age Proportions of Respondents", 
       x = "Age",
       y = "Number of Respondents"
       ) +
  theme_minimal()
```

```{r, echo=FALSE}
clean_strat_data %>% 
  ggplot(aes(x = gender)) + 
  geom_bar(colour = "black", fill = "firebrick2") + 
  labs(title = "Graph 8: Gender Proportions of Respondents", 
       x = "Gender",
       y = "Number of Respondents"
       ) + 
  theme_minimal()
```

```{r, echo=FALSE}
clean_strat_data %>% 
  ggplot(aes(x = race_ethnicity)) + 
  geom_bar(colour = "black", fill = "orangered1") + 
  labs(title = "Graph 9: Races of Respondents", 
       x = "Race",
       y = "Number of Respondents"
       ) + 
  coord_flip() + 
  theme_minimal()
```


```{r, echo=FALSE}
clean_strat_data %>% 
  ggplot(aes(x = language)) + 
  geom_bar(colour = "black", fill = "springgreen4") + 
  labs(title = "Graph 10: Languages Used by Respondents", 
       x = "Language Used at Home",
       y = "Number of Respondents"
       ) + 
  theme_minimal()

```

```{r, echo=FALSE}
clean_strat_data %>% 
  ggplot(aes(x = census_region)) + 
  geom_bar(colour = "black", fill = "mediumseagreen") + 
  labs(title = "Graph 11: Regional Distribution of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       ) + 
  theme_minimal()
```


## 3 Model Discussion and Development 

# 3.1 Regression Model

```{r, include=FALSE}
survey_glm <- glm(as.numeric(vote_2020 == "Donald Trump") ~ 
                    age_group + 
                    gender +
                    census_region + 
                    race_ethnicity + 
                    language,
                  family = 'binomial',
                  data = clean_data
)
```

```{r, include = FALSE}
survey_glm_plot <- glm(vote_2020 ~ 
                    age_group + 
                    gender +
                    census_region + 
                    race_ethnicity + 
                    language,
                  family = 'binomial',
                  data = clean_data
)
```

# 3.2 Model Validation

```{r, include = FALSE}
cv.glm(clean_data, survey_glm, K = 10)
```

```{r, include = FALSE}
test_data_MSPE <- clean_data %>%
  mutate(id = row_number())

test_data_msres <- clean_data %>% 
  mutate(id = row_number())
```

```{r, warning = FALSE, include = FALSE}
# Splicing Data into Testing and Training Set
set.seed(5799893)
glm_test_MSPE <- sample_n(test_data_MSPE, 1295)
glm_test_msres <- test_data_msres %>%
  anti_join(test_data_MSPE)
```

```{r, include = FALSE}
#Model validation, comparing MSPE and MSres
# fitting sample dataset to our model
glm_test1 <- glm(as.numeric(vote_2020 == "Donald Trump") ~ 
                    age_group + 
                    gender +
                    census_region + 
                    race_ethnicity + 
                    language,
                  family = 'binomial',
                  data = test_data_msres)

glm_test2 <- glm(as.numeric(vote_2020 == "Donald Trump") ~ 
                    age_group + 
                    gender +
                    census_region + 
                    race_ethnicity + 
                    language,
                  family = 'binomial',
                  data = test_data_MSPE)
                      
#calculation of the mspe for sample dataset
mspe = sum(resid(glm_test2)^2)/ length(test_data_MSPE$vote_2020)
#calculation of the MSres for our main dataset
# 13 represent the degrees of freedom in our model 
msres = sum(resid(glm_test1)^2)/(length(test_data_msres$vote_2020) - 13)
mspe
msres
```

```{r, include = FALSE}
summary(survey_glm)
```

```{r, echo = FALSE}
summ(model = survey_glm, model.fit = FALSE)
```


# 4 results

# Regression
```{r, echo = FALSE}
plot_summs(survey_glm_plot, plot.distributions = TRUE, inner_ci_level = .95)
```

```{r, echo = FALSE}
plot(survey_glm, which = 4, id.n = 3)
```

# Forecast

```{r, include = FALSE}
# Create Cells
cell_counts <- clean_strat_data %>% 
  group_by(age_group, gender, census_region, race_ethnicity, language) %>%
  count() %>%
  mutate(proportion = n/2603150
         )

```

```{r,include=FALSE}
# Create Prediction Vector
predictions <- predict.glm(survey_glm, se.fit = TRUE, cell_counts, type = "response")
```


```{r, include=FALSE}
# Add Predictions to cell counts
cell_counts2 <- cbind(cell_counts, predictions$fit, predictions$se.fit)
```

```{r, include=FALSE}
# First Forecasting Result
vote_pred <- cell_counts2$proportion * cell_counts2$...8
sum(vote_pred)
```

```{r, include=FALSE}
lower_pred = cell_counts2$...8 - cell_counts2$...9
upper_pred = cell_counts2$...8 + cell_counts2$...9
cell_counts2 <- cbind(cell_counts2, lower_pred, upper_pred)
```

```{r, include=FALSE}
cell_counts2 <- cell_counts2 %>% rename(
  prediction = ...8,
  StdError = ...9,
  LowerBound = ...10,
  UpperBound = ...11
)
```

```{r, include = FALSE}
# Errors
lower_vote_pred <- cell_counts2$proportion * cell_counts2$LowerBound
sum(lower_vote_pred)
upper_vote_pred <- cell_counts2$proportion * cell_counts2$UpperBound
sum(upper_vote_pred)
```


















