---
title: "TBD"
subtitle: "TBD"
author: "TBD"
thanks: "Code and data are available at: LINK."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: |
  | First sentence. Second sentence. Third sentence. Fourth sentence. 
output:
  bookdown::pdf_document2:
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Packages
library(haven)
library(tidyverse)
library(labelled)
library(jtools)
```


```{r}
# Graph Vote Distribution
clean_data %>% 
  ggplot(aes(x = vote_2020)) + 
  geom_bar() + 
  labs(title = "Vote Decisions of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       )
prop.table(table(clean_data$vote_2020))
```



```{r}
# Graph Age Distribution
clean_data %>% 
  ggplot(aes(x = age_group)) + 
  geom_bar() +
  labs(title = "Age Proportions of Respondents", 
       x = "Age",
       y = "Number of Respondents"
       )
```


```{r}
# Graph Gender Distribution
clean_data %>% 
  ggplot(aes(x = gender)) + 
  geom_bar() + 
  labs(title = "Gender Proportions of Respondents", 
       x = "Gender",
       y = "Number of Respondents"
       )
prop.table(table(clean_data$gender))
```


```{r}
# Graph Race Distribution
clean_data %>% 
  ggplot(aes(x = race_ethnicity)) + 
  geom_bar() + 
  labs(title = "Races of Respondents", 
       x = "Race",
       y = "Number of Respondents"
       ) + 
  coord_flip()
prop.table(table(clean_data$race_ethnicity))
```



```{r}
# Graph Language Distribution
clean_data %>% 
  ggplot(aes(x = language)) + 
  geom_bar() + 
  labs(title = "Languages Used by Respondents", 
       x = "Language Used at Home",
       y = "Number of Respondents"
       )
prop.table(table(clean_data$language))

```


```{r}
# Graph Regional Distribution
clean_data %>% 
  ggplot(aes(x = census_region)) + 
  geom_bar() + 
  labs(title = "Regional Distribution of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       )

prop.table(table(clean_data$census_region))
```


```{r}
# Create Regression Model
survey_glm <- glm(as.numeric(vote_2020 == "Donald Trump") ~ 
                    age_group + 
                    gender +
                    census_region + 
                    race_ethnicity + 
                    language,
                  family = 'binomial',
                  data = clean_data
)

summary(survey_glm)
```


POST STRAT DATA

```{r}
clean_strat_data %>% 
  ggplot(aes(x = age_group)) + 
  geom_bar() +
  labs(title = "Age Proportions of Respondents", 
       x = "Age",
       y = "Number of Respondents"
       )
prop.table(table(clean_strat_data$age_group))
```



```{r}
clean_strat_data %>% 
  ggplot(aes(x = gender)) + 
  geom_bar() + 
  labs(title = "Gender Proportions of Respondents", 
       x = "Gender",
       y = "Number of Respondents"
       )
prop.table(table(clean_strat_data$gender))
```


```{r}
clean_strat_data %>% 
  ggplot(aes(x = race_ethnicity)) + 
  geom_bar() + 
  labs(title = "Races of Respondents", 
       x = "Race",
       y = "Number of Respondents"
       ) + 
  coord_flip()
prop.table(table(clean_strat_data$race_ethnicity))
```


```{r}
clean_strat_data %>% 
  ggplot(aes(x = language)) + 
  geom_bar() + 
  labs(title = "Languages Used by Respondents", 
       x = "Language Used at Home",
       y = "Number of Respondents"
       )
prop.table(table(clean_strat_data$language))

```



```{r}
clean_strat_data %>% 
  ggplot(aes(x = census_region)) + 
  geom_bar() + 
  labs(title = "Regional Distribution of Respondents", 
       x = "Vote Choice",
       y = "Number of Respondents"
       )
prop.table(table(clean_strat_data$census_region))
```


```{r}
# Create Cells
cell_counts <- clean_strat_data %>% 
  group_by(age_group, gender, census_region, race_ethnicity, language) %>%
  count() %>%
  mutate(proportion = n/2603150
         )

```

```{r,include=FALSE}
# Create Prediction Vector
predictions <- predict.glm(survey_glm, cell_counts, type = "response")
```

```{r}
# Add Predictions to cell counts
cell_counts2 <- cbind(cell_counts, predictions)
```

```{r}
# First Forecasting Result
vote_pred <- cell_counts2$proportion * cell_counts2$...8
sum(vote_pred)
```
